name = "highroll-api-dev"
main = "src/worker.ts"
compatibility_date = "2026-02-03"
workers_dev = true

# [vars]
# ALLOWED_ORIGINS = "https://highroll-ui.pages.dev,https://highroll.reak1161.com,https://reak1161.com,https://www.reak1161.com,https://api.reak1161.com"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[durable_objects.bindings]]
name = "LOBBY_INDEX"
class_name = "LobbyIndexDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["LobbyIndexDO"]

[env.production]
name = "highroll-api"

# [env.production.vars]
# ALLOWED_ORIGINS = "https://highroll-ui.pages.dev,https://highroll.reak1161.com,https://reak1161.com,https://www.reak1161.com"

[[env.production.durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[env.production.durable_objects.bindings]]
name = "LOBBY_INDEX"
class_name = "LobbyIndexDO"
